--CHECKER
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS foto_produk;
DROP TABLE IF EXISTS produk;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS trx;
DROP TABLE IF EXISTS alamat;
DROP TABLE IF EXISTS toko;
DROP TABLE IF EXISTS detail_trx;
DROP TABLE IF EXISTS log_produk;




